# This play is for the Kali VM image builder variant, not vagrant
---
- hosts: kali
  roles:
    - basics_kali
    - dotfiles_kali
    - rustup_kali
    - starship_kali
    - navi
    - atuin_kali
    - yazi_kali
    - lazyvim
    - guac_kali
